language: node_js

node_js:
  - node
  - lts/*
  - 10
  - 8

script:
  - npm run coverage
  
after_success:
  - npm run coverage:report
  - npm run semantic-release

notifications:
  webhooks:
    urls:
      - https://git.dvbris.com/?semver
      - https://git.geraintwhite.co.uk/?semver
      - https://git.oliverfaircliff.com/?semver
    on_success: always
    on_failure: never
