language: node_js
sudo: false

node_js:
  - '0.10'
  - '0.11'
  - '0.12'

before_install:
  - npm i -g npm@^2.0.0

before_script:
  - npm prune


script:
  - npm run coverage

after_success:
  - npm run coverage:report
  - npm run semantic-release

notifications:
  webhooks:
    urls:
      - https://git.dvbris.com
      - https://git.geraintwhite.co.uk
      - https://git.oliverfaircliff.com
    on_success: always
    on_failure: never

deploy:
  provider: npm
  email: mail@dvbris.com
  api_key:
    secure: pBSl61nn+XSb3BMAufCShtS/8Rnw8t8xsovTWExxYxyBNQBsAjhsfpBJjyIGiM+TuoOiRFJd6t+nfGKJi3aJVwQ5XdCYMY88ppyRM6rdwJintPQOjSgxwvfmG3pRJCJ2/Y+m233sAzf6GGh4G4XhCv1i8WuTLNhjh7pq6pF+V6g=
  on:
    tags: true
    repo: itsapi/github-listener
