language: node_js
sudo: false

cache:
  directories:
    - node_modules

node_js:
  - '4'
  - '5'

before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run coverage
after_success:
  - npm run coverage:report
  - npm run semantic-release

notifications:
  webhooks:
    urls:
      - https://git.dvbris.com/?semver
      - https://git.geraintwhite.co.uk/?semver
      - https://git.oliverfaircliff.com/?semver
    on_success: always
    on_failure: never
