language: node_js

node_js:
  - "0.11"
  - "0.10"

before_script:
  - "npm install -g istanbul"
  - "npm install -g codeclimate-test-reporter"

after_script:
  - "istanbul cover tests.js"
  - "codeclimate < coverage/lcov.info"

notifications:
  webhooks:
    urls:
      - http://geraint.ngrok.com/issue-17
      # - http://git.dvbris.com
      # - http://git.geraintwhite.co.uk
      # - http://git.oliverfaircliff.com
    on_success: always
    on_failure: never
