language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8 # stable
  - 6 # LTS
  - 4 # maintenance

before_script:
  - npm prune
script:
  - npm run coverage
after_success:
  - npm run coverage:report
  - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release

notifications:
  webhooks:
    urls:
      - https://git.dvbris.com/?semver
      - https://git.geraintwhite.co.uk/?semver
      - https://git.oliverfaircliff.com/?semver
    on_success: always
    on_failure: never
