language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm install
  - npm test
  - npm run cov

notifications:
  webhooks:
    urls:
      - http://geraint.ngrok.com/issue-17
      # - http://git.dvbris.com
      # - http://git.geraintwhite.co.uk
      # - http://git.oliverfaircliff.com
    on_success: always
    on_failure: never
